### ISSUE TITLE
Adicionar campo de Reclamações - Create Service Schedule

### ISSUE THREAD

**Issue by pabloedu01** [TUNAP-Brasil/Frontend-Tunapconnect#82]
https://github.com/TUNAP-Brasil/Frontend-Tunapconnect/assets/1905753/95a494e1-8219-4445-a29f-5967b6519726

**Comment by pabloedu01** [comment]
a API para ser usada é
{{host}}/api/claim-service

![image](https://github.com/TUNAP-Brasil/Frontend-Tunapconnect/assets/1905753/9eed0d2b-530c-4c55-9f17-aca8d80126d8)
Nesse formato

**Comment by kleberfreire** [comment]
Poderia mudar o status de erro quando existir so restornar com created

**Comment by pabloedu01** [comment]
@serpams altera pra 202

**Comment by pabloedu01** [comment]
Concluído
